[package]
name = "stringproc"
version = "0.1.0"
authors = ["Elijah <woelbingelijah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timer = "0.1.3"
chrono = "0.2.25"

